
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

/* Automatically generated by glib-mkenums */

#ifndef _DMAP_ENUMS_H
#define _DMAP_ENUMS_H

#include <glib-object.h>

G_BEGIN_DECLS

/* enumerations from "dmap-cc.h" */
GType dmap_content_code_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_CONTENT_CODE (dmap_content_code_get_type())

/* enumerations from "dmap-connection.h" */
GType dmap_connection_state_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_CONNECTION_STATE (dmap_connection_state_get_type())

/* enumerations from "dmap-control-player.h" */
GType dmap_control_repeat_state_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_CONTROL_REPEAT_STATE (dmap_control_repeat_state_get_type())
GType dmap_control_play_state_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_CONTROL_PLAY_STATE (dmap_control_play_state_get_type())

/* enumerations from "dmap-db.h" */
GType dmap_db_id_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_DB_ID (dmap_db_id_get_type())

/* enumerations from "dmap-error.h" */
GType dmap_error_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_ERROR (dmap_error_get_type())

/* enumerations from "dmap-mdns-browser.h" */
GType dmap_mdns_browser_error_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_MDNS_BROWSER_ERROR (dmap_mdns_browser_error_get_type())

/* enumerations from "dmap-mdns-publisher.h" */
GType dmap_mdns_publisher_error_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_MDNS_PUBLISHER_ERROR (dmap_mdns_publisher_error_get_type())

/* enumerations from "dmap-mdns-service.h" */
GType dmap_mdns_service_type_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_MDNS_SERVICE_TYPE (dmap_mdns_service_type_get_type())
GType dmap_mdns_service_transport_protocol_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_MDNS_SERVICE_TRANSPORT_PROTOCOL (dmap_mdns_service_transport_protocol_get_type())

/* enumerations from "dmap-record.h" */
GType dmap_media_kind_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_MEDIA_KIND (dmap_media_kind_get_type())

/* enumerations from "dmap-share.h" */
GType dmap_share_auth_method_get_type (void) G_GNUC_CONST;
#define DMAP_TYPE_DMAP_SHARE_AUTH_METHOD (dmap_share_auth_method_get_type())
G_END_DECLS

#endif /* _DMAP_ENUMS_H */

/* Generated data ends here */

