/* Machine-generated by ./generate-test-suites; do not edit. */

#include <check.h>
#include <glib.h>
#include <stdlib.h>
#include <libdmapsharing/dmap.h>

#include "../libdmapsharing/daap-connection-suite.h"
#include "../libdmapsharing/dmap-md5-suite.h"
#include "../libdmapsharing/dmap-utils-suite.h"

static void
debug_null (const char *log_domain,
            GLogLevelFlags log_level,
            const gchar *message,
            gpointer user_data)
{
}

void run_suite (Suite *s)
{
        int nf;
        SRunner *sr;

        sr = srunner_create(s);
        srunner_run_all(sr, CK_NORMAL);
        nf = srunner_ntests_failed(sr);
        srunner_free(sr);
        if (nf != 0) {
                exit (EXIT_FAILURE);
	}
}

int main(void)
{
        g_log_set_handler ("libdmapsharing", G_LOG_LEVEL_DEBUG, debug_null, NULL);
        g_log_set_handler (NULL, G_LOG_LEVEL_DEBUG, debug_null, NULL);
        run_suite(dmap_test_daap_connection());
        run_suite(dmap_test_dmap_md5());
        run_suite(dmap_test_dmap_utils());

        exit (EXIT_SUCCESS);
}
